export enum MicroservicePattern {
  nextSong = 'nextSong',
  pozdro = 'pozdro',
  playSilence = 'playSilence',
  playDj = "playDj",
  channelAppear = "channelAppear",
  channelDisappears = "channelDisppear",
  deleteQueuedTrack = 'deleteQueuedTrack',
  getCurrentTrack = "getCurrentTrack",
  setCurrentTrack = "setCurrentTrack",
  addToQueue = "addToQueue",
  setSilenceCount = "setSilenceCount",
  getQueue = "getQueue",
  removeFromQueue = "removeFromQueue",
  getSilenceCount = "getSilenceCount",
  createTrack = "createTrack",
  downloadTrack = "downloadTrack",
  fuckYou = "fuckYou",
  heart = "heart",
  queueTrack = "queueTrack",
  thumbUp = "thumbUp",
  deleteTrack = "deleteTrack",
  playTrack = "playTrack",
  thumbDown = "thumbDown"
}
